[package]
name = "aoc-rust"
authors = ["Annabelle Cloutier"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.11.0"
itertools = "0.11.0"
md5 = "0.7.0"
num = "0.4.1"
regex = "1.9.5"
